import type { Metadata } from "next";
import localFont from "next/font/local";
import { DM_Sans } from "next/font/google"
import {Roboto_Flex} from "next/font/google"
import {Inter} from "next/font/google"
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({
  subsets: ['latin'],
  weight: ['400','500'],
  variable: '--font-inter'
})
const robotoFlex = Roboto_Flex({
  subsets: ['latin'],
  weight: ["400", "600"],
  variable: '--font-robotoflex'
})

const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['400','600'],
  variable: '--font-dmsans'
})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dmSans.variable} ${robotoFlex.variable} ${inter.variable} antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
